name: free-programming-books-lint

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install fpb-lint
        run: npm install -g free-programming-books-lint
      - name: Lint books
        id: books
        run: fpb-lint ./books/
        continue-on-error: true
      - name: Lint casts
        id: casts
        run: fpb-lint ./casts/
        continue-on-error: true
      - name: Lint courses
        id: courses
        run: fpb-lint ./courses/
        continue-on-error: true
      - name: Lint more
        id: more
        run: fpb-lint ./more/
        continue-on-error: true

      - name: Comment PR
        if: steps.books.outcome == 'failure' || steps.casts.outcome == 'failure' || steps.courses.outcome == 'failure' || steps.more.outcome == 'failure'
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "PR: needs rebase"
          removeOnDirtyLabel: "PR: ready to ship"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has lint issues, please resolve those before we can evaluate the pull request."
          commentOnClean: "Conflicts have been resolved. A maintainer will review the pull request as soon as possible."
